server:
  port: 8085  # Change the port as per your requirement

spring:
  cloud:
    gateway:
      routes:
        - id: SwiggyWebClient
          uri: lb://SWIGGYWECLIENT
          predicates:
            - Path=/swiggy/**
          filters:
            - name: AuthenticationFilter

        - id: restaurant-service
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/restaurant/**
          filters:
            - name: AuthenticationFilter

        - id: security-service
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
